name: Local
variables:
  - name: base_url
    value: http://localhost:5100
  - name: admin_token
    value: ""
  - name: user1_token
    value: ""
  - name: user2_token
    value: ""
  - name: user3_token
    value: ""
  - name: admin_user_id
    value: ""
  - name: user1_id
    value: ""
  - name: user2_id
    value: ""
  - name: user3_id
    value: ""
  - name: org_id
    value: ""
  - name: org_id_2
    value: ""
  - name: invitation_id
    value: ""
  - name: invitation_id_2
    value: ""
  - name: license_id
    value: ""
  - name: license_id_2
    value: ""
  - name: license_id_auto
    value: ""
